const icons = {
  typeName: [
    'Bug',
    'Dark',
    'Dragon',
    'Electric',
    'Fairy',
    'Fighting',
    'Fire',
    'Flying',
    'Ghost',
    'Grass',
    'Ground',
    'Ice',
    'Normal',
    'Poison',
    'Psychic',
    'Rock',
    'Steel',
    'Water',
  ],
  srcType: [
    'images/Tag-Bug.svg',
    'images/Tag-Dark.svg',
    'images/Tag-Dragon.svg',
    'images/Tag-Electric.svg',
    'images/Tag-Fairy.svg',
    'images/Tag-Fighting.svg',
    'images/Tag-Fire.svg',
    'images/Tag-Flying.svg',
    'images/Tag-Ghost.svg',
    'images/Tag-Grass.svg',
    'images/Tag-Ground.svg',
    'images/Tag-Ice.svg',
    'images/Tag-Normal.svg',
    'images/Tag-Poison.svg',
    'images/Tag-Psychic.svg',
    'images/Tag-Rock.svg',
    'images/Tag-Steel.svg',
    'images/Tag-Water.svg',
  ],
  typeSrc: [
    { name: 'Bug', imgSrc: 'images/Tag-Bug.svg' },
    { name: 'Dark', imgSrc: 'images/Tag-Dark.svg' },
    { name: 'Dragon', imgSrc: 'images/Tag-Dragon.svg' },
    { name: 'Electric', imgSrc: 'images/Tag-Electric.svg' },
    { name: 'Fairy', imgSrc: 'images/Tag-Fairy.svg' },
    { name: 'Fighting', imgSrc: 'images/Tag-Fighting.svg' },
    { name: 'Fire', imgSrc: 'images/Tag-Fire.svg' },
    { name: 'Flying', imgSrc: 'images/Tag-Flying.svg' },
    { name: 'Ghost', imgSrc: 'images/Tag-Ghost.svg' },
    { name: 'Grass', imgSrc: 'images/Tag-Grass.svg' },
    { name: 'Ground', imgSrc: 'images/Tag-Ground.svg' },
    { name: 'Ice', imgSrc: 'images/Tag-Ice.svg' },
    { name: 'Normal', imgSrc: 'images/Tag-Normal.svg' },
    { name: 'Poison', imgSrc: 'images/Tag-Poison.svg' },
    { name: 'Psychic', imgSrc: 'images/Tag-Psychic.svg' },
    { name: 'Rock', imgSrc: 'images/Tag-Rock.svg' },
    { name: 'Steel', imgSrc: 'images/Tag-Steel.svg' },
    { name: 'Water', imgSrc: 'images/Tag-Water.svg' },
  ],
  eggs: [
    'images/egg2km.svg',
    'images/egg5km.svg',
    'images/egg10km.svg',
  ],
  eggKm: [
    '2 km',
    '5 km',
    '10 km',
  ],
};
export default icons;
